### ISSUE TITLE
Список полей за изменением которых будет производиться слежение

### ISSUE THREAD

**Issue by kosenka** [lav45/yii2-activity-logger#14]
Спасибо за логгер, но хотелось бы добавить функционал.
Сейчас есть список полей для отслеживания в котором перечисляются имена полей, например:
 'name', 'id' и т.д.
Хотелось бы получать их "осмысленные" значение public function attributeLabels() у модели.

**Comment by lav45** [comment]
Именно так и работает. Возможно вы не заполнили `entityMap` в настройках.

```php
return [
    'modules' => [
        /**
         * Модуль будет использоваться для просмотра логов
         */
        'logger' => [
            'class' => \lav45\activityLogger\modules\Module::class,

            // Список моделей которые логировались
            'entityMap' => [
                'news' => 'common\models\News',
            ],
        ]
    ],
];
```

**Comment by kosenka** [comment]
entityMap у меня заполнено:
    'modules' => [
        'logger' => [
            'class' => \lav45\activityLogger\modules\Module::class,
            // Список моделей которые логировались
            'entityMap' => [
                'Hospitals' => 'models\Hospitals',
                'Doctors' => 'models\Doctors',
            ],
        ]
    ],

Но в самой модели имя таблицы у меня такое:
        /**
         * @inheritdoc
         */
        static public function tableName()
        {
            return '{{%Hospitals}}';
        }

Так же в конфиге задан префикс для таблиц:
return [
    'class' => 'yii\db\Connection',
    'charset' => 'utf8',
    'tablePrefix' => 'mp_',
];

И вот логгер, кажется, не корректно "отрабатывает" получение имени таблицы.

Я заменил в поведении модели получение имени таблицы:
        public function behaviors()
        {
            return [
                [
                    'class' => \lav45\activityLogger\ActiveLogBehavior::class,
                    // Если необхадимо изменить стандартное значение `entityName`
                    'getEntityName' => function () {
                        //return static::tableName();
                        return self::getTableSchema()->fullName;
                    },

Имя таблицы стало возвращаться корректно 'mp_Hospitals' и запись в таблицу '{{%activity_log}}' пишется нормально, но при показе /logger/default/index все равно не корректно отображаются поля модели...

Если в настройках модуля сделать так:
'logger' => [
            'class' => \lav45\activityLogger\modules\Module::class,
            // Список моделей которые логировались
            'entityMap' => [
                'mp_Hospitals' => 'models\Hospitals',
                'Doctors' => 'models\Doctors',
            ],
        ]
То вываливается ошибка: Class 'models\Hospitals' not found
