### ISSUE TITLE
Отсутствует перевод в messages для deleted

### ISSUE THREAD

**Issue by Arnoldinya** [lav45/yii2-activity-logger#16]
https://github.com/lav45/yii2-activity-logger/blob/34cd095c3e9f0cfd571f6b3c2ec2d56b0fa1f97a/src/ActiveLogBehavior.php#L215

**Comment by user14GG88man** [comment]
Сдается мне, что автор благополучно забил на модуль...Сам имею несколько вопросов, но как-то решаю их по мере обнаружения.

**Comment by nohnaimer** [comment]
Не забил, а нету времени на данный момент. Pull request приветствуется, не надо все держать в себе 😉

**Comment by lav45** [comment]
> https://github.com/lav45/yii2-activity-logger/blob/34cd095c3e9f0cfd571f6b3c2ec2d56b0fa1f97a/src/ActiveLogBehavior.php#L215

Перевод происходит при отображении данных
https://github.com/lav45/yii2-activity-logger/blob/master/src/modules/views/default/_item.php#L32
